sudo: required
language: python
python:
  - "2.7"

services:
  - docker

# command to install dependencies
install:
  - make install

before_install:
  - docker pull mdillon/postgis

# command to run tests
script:
  - make git-attributes
  - make lint
  - make tests-docker-setup-db
  - make tests

# deploy to pypi
deploy:
  provider: pypi
  user: kdeininger
  on:
    tags: true
    branch: master
  password:
    secure: CYZ7d1mLkVArXOF3vC7fCbC21uljK9cKvX8gKjgBir09o2ip1kC8lm+MaBKRBVgQiZUFQ5J7zRO30B8554i3JG6c0AqHIVHmTfarLOLaJOGVe3D314htg5u0CiKbD4Gu3mGxk04crwUoHv2N7IXK7LAy7LfgJM7Carna6qVL/Ap8oXL0AwEgHVBnbLzju4xJAxNcZAQuKSnBR2+hXNUuWzWzZQkupP5ZxnEkpO6E8FoSxuQtuSmhSuzY0y0L73beQ2ptG8hQN8pg1cVrC7YIVtPZxPF7zmGVsfAqTE1J6wqQpNt+RQdg4lziCjm0JT4Tm8TnYjoTVuVSb3uztPwR3P6R4QwGmE7tKhsLGqEdTpgSUrqg//Zh9DCO1HQ1byBMJyPpq94K7X7qWtsbp9ZVdf5VvjTGZ6pjcb0pDGOSoNiYrXvTzZd3Pv1M+rxx8af3mjlzZDFUtWBw/qR5Fv2/CUpXIloipLo7VIvkyZgObu3/+OzvGFRGRn7WvsvY6ItuQp5b2jtvc6M8GmE89JMntLr3z+CrpyHSf8TtQsb12cYlQx6lURKgJ6ncYQqKX65ASvfsBnJvVEx2INFD6oe9DJZhmCryladgaoiFgF19OjJK9YIPxIxSPmiFlSd2wq0IaDilqW/3yGXOU/0RrzQ3CWp1jZnXX7hod2WL1pHjgxI=
  distributions: "sdist bdist_wheel"

# configure notifications
notifications:
  email: false
