sudo: required
language: python

python:
  - "2.7"
  - "3.6"

services:
  - docker

env:
  global:
  - TRAVIS_USERNAME=sbrunner
  - secure: "EuOwzJOL1IUt4j8PYxsjIa9iTiGxHN1IwuhIyKJ2QZy3kO2/VQP7z1CUPAjxiXSCA8kwhK+Xq2mqwRfCPBH/CHHE6gZuHRkqd5wOn4ireifYFoBt6MGBPZvTr5S5ha2POUMXuBqpbzey5bMUNUabrS9VbUGSmCNnFnNu/gnPOi31Fw3PIVdjI1+k2JqbBMbDHlUYCDR2lInisGQaQE3mCrs8kmCa4h1FhamANCIHarrxkNsEH5YzBGbnJUbCQrHEEyVq6oNO1jcMrRf3KJR2hwgg8onr9t9/pDFbYUhuPyrewp3UOmmqWPkfR3Z9So69Tcgkz4+G0XXJizF/dQLJZTRWjdcZnI6aeLj8a32JcUPlrDEqjLajK+8rkgv1pD01I+8FyQnVTYARGlovZ6gn+5UTx3SddByEVARIGiOkLY9RrTWe1AuImMBCYYXKKWL4OIvW02fILMWU1JuGGqa+CAUSpRznfZc1bCKbS6iL1xtsRX9dnHkg4S5NKhXlbYYsXhyuztv8rkh/jXEYaqptHtQU3D1+cyD0bT5Wx5PhZSKQJ48p73+SZXHXGeHGdV/P0mT7YhNxwaQA6cbCH65rOQZ1zQaF6/N2CNgYDiJp5aYzLjol9hncH+WJh2AwdhujFewgxbTO8dOypXrNTlM1EfTBZ6oQriLSWbXbMI6VsUc="

# command to install dependencies
install:
  - sudo service postgresql stop
  - make install

# command to run tests
script:
  - make git-attributes
  - make lint
  - make tests-docker-setup-db
  - make tests

after_success:
  - make doc

before_deploy:
  - pip install sphinxcontrib-versioning 'Sphinx<1.6'

# deploy to pypi
deploy:
- provider: script
  script: sphinx-versioning push doc/source/ gh-pages doc
  on:
    branch: master
    repo: camptocamp/pyramid_oereb
- provider: script
  script: sphinx-versioning push doc/source/ gh-pages doc
  on:
    tags: true
    repo: camptocamp/pyramid_oereb
- provider: pypi
  server: https://upload.pypi.org/legacy/
  user: kdeininger
  password:
    secure: U9VKY1WXnpEyarOjju/weA701WjM3Ok55qoV0EB3SzEh5Bg8Hne09GY9Kl0rzhCsaLTb8jp2tEE+oihWHmU+JH3AB/dodFRL5WCcSbmoFFsE9KbTUgMFdGZ6fMmL90CIzXtiuKTEMdUBvEMFr9qR3GNGRonKD3G6uwbPpiK2TRCNpbjTx5uIl4pfsRAQXJrAsZMGX9907ghBHYHntf+SIM0QrRf1DCHS3yqb03QG9hSZguEhX98UzJVz8Q7ls7WhhIwhCWgG7inr+I5Kq8j9ktuJU1T0Fj4StmaKW/YZbzDxArkiSYpphOvNptp7wZX7OAmV9OuNS7EzedwhaE+XeTO8UdgREKWyq+i4ydU20cQbCSEZeDjDZrRi/9HteXTbTK2hWw8oQ8d0Rwq9kz/2trle4M33IA7Skbxq6oknwShbPGEzKiHXu8R8+oump5jtza77/zR4XnzuJW0BbHpSQhVrCAhxCCMZEJmUxMSn2HIovoF29lZOzrpDIBz2Qa6VHBzUCAvdLGOGSoib3/V7zkxWe9AOJWrP0LK29MiEHpqgOQXxnuGQESJDhm71kQXvpHHBhTnOxtPEbytMiygnN9LypnnMBl3GV6hxv0ErF28nwJhyBaiL3JFeIUK1fmOwL8xc7587/2212Li3R1IZS/pSSn9OUCgsfGxvkiuxsjg=
  on:
    tags: true
    repo: camptocamp/pyramid_oereb
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true
- provider: script
  script: travis/deploy-daily-pipy-build.sh
  on:
    repo: camptocamp/pyramid_oereb
    branch: master
    condition: '"${TRAVIS_EVENT_TYPE}" = cron'

# configure notifications
notifications:
  email: false
