throwErrorOnExtraParameters: true


templates:
    A4 portrait: !template
        reportTemplate: A4_Portrait.jrxml
        attributes:
            CreationDate: !string {}
            Signature: !string &optStr
                default: ''
            ConcernedTheme: !datasource
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            NotConcernedTheme: !datasource
                attributes:
                    Code: !string {}
                    Text: !datasource
                        attributes:
                            Text: !string {}
                            Language: !string {}
            ThemeWithoutData: !datasource
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            isReduced: !boolean {}
            LogoPLRCadastre: *optStr
            LogoPLRCadastreRef: *optStr
            FederalLogo: *optStr
            FederalLogoRef: *optStr
            CantonalLogo: *optStr
            CantonalLogoRef: *optStr
            MunicipalityLogo: *optStr
            MunicipalityLogoRef: *optStr
            ExtractIdentifier: !string {}
            QRCode: *optStr
            QRCodeRef: *optStr
            GeneralInformation: !datasource #/definitions/MultilingualMText
                default: []
                attributes:
                    Language: !string {}
                    Text: !string {}
            BaseData: !datasource #/definitions/MultilingualMText
                attributes:
                    en: !string
                        default: ''
                    de: !string
                        default: ''
                    fr: !string
                        default: ''
                    it: !string
                        default: ''
            Glossary: !datasource
                default: []
                attributes:
                    Title: !datasource #/definitions/MultilingualText
                        attributes:
                            Language: !string {}
                            Text: !string {}
                    Content: !datasource #/definitions/MultilingualText
                        attributes:
                            Language: !string {}
                            Text: !string {}
            RealEstate_Number: !string {}
            RealEstate_IdentDN: !string {}
            RealEstate_EGRID: !string {}
            RealEstate_Type: !string {}
            RealEstate_Canton: !string {}
            RealEstate_Municipality: !string {}
            RealEstate_SubunitOfLandRegister: !string
                default: ''
            RealEstate_FosNr: !string {}
            RealEstate_MetadataOfGeographicalBaseData: !string
                default: ''
            RealEstate_LandRegistryArea: !string {}
            RealEstate_Limit: !string #/definitions/MultiSurface"
                default: '{}'
            RealEstate_RestrictionOnLandownership_Information: !string #/definitions/MultilingualMText
                default: ''
            RealEstate_RestrictionOnLandownership_Theme: !string #/definitions/Theme
                default: ''
            RealEstate_RestrictionOnLandownership_SubTheme: !string
                default: ''
            RealEstate_RestrictionOnLandownership_TypeCode: !string #/definitions/RestrictiontypeCode
                default: ''
            RealEstate_RestrictionOnLandownership_TypeCodelist: !string
                default: ''
            RealEstate_RestrictionOnLandownership_Lawstatus: !string #/definitions/Lawstatus
                default: ''
            RealEstate_RestrictionOnLandownership_Area: !string #/definitions/Area
                default: ''
            RealEstate_RestrictionOnLandownership_PartInPercent: !float
                default: -1
            RealEstate_RestrictionOnLandownership_Symbol: !string
                default: ''
            RealEstate_RestrictionOnLandownership_SymbolRef: !string
                default: ''
            RealEstate_RestrictionOnLandownership_Geometry: !datasource
                default: []
                attributes:
                    Point: !string {} #/definitions/PointPropertyType
                    Line: !string {} #/definitions/CurvePropertyType
                    Surface: !string {} #/definitions/SurfacePropertyType
                    Lawstatus: !string {} #/definitions/Lawstatus
                    MetadataOfGeographicalBaseData: !string {}
                    ResponsibleOffice_Name: !string {} #/definitions/MultilingualText
                    ResponsibleOffice_OfficeAtWeb: !string {} #/definitions/WebReference
                    ResponsibleOffice_UID: !string #/definitions/UID
                        default: ''
                    ResponsibleOffice_Line1: !string
                        default: ''
                    ResponsibleOffice_Line2: !string
                        default: ''
                    ResponsibleOffice_Street: !string {}
                    ResponsibleOffice_Number: !string {}
                    ResponsibleOffice_PostalCode: !string {}
                    ResponsibleOffice_City: !string {}
            RealEstate_RestrictionOnLandownership: !datasource
                default: []
                attributes:
                  TextAtWeb: !string {} #/definitions/MultilingualUri
                  Lawstatus: !string {} #/definitions/Lawstatus
            RealEstate_RestrictionOnLandownership_ResponsibleOffice_Name: !string #/definitions/MultilingualText
                default: ''
            RealEstate_RestrictionOnLandownership_ResponsibleOffice_OfficeAtWeb: !string #/definitions/WebReference
                default: ''
            RealEstate_RestrictionOnLandownership_ResponsibleOffice_UID: !string #/definitions/UID
                default: ''
            RealEstate_RestrictionOnLandownership_ResponsibleOffice_Line1: !string
                default: ''
            RealEstate_RestrictionOnLandownership_ResponsibleOffice_Line2: !string
                default: ''
            RealEstate_RestrictionOnLandownership_ResponsibleOffice_Street: !string
                default: ''
            RealEstate_RestrictionOnLandownership_ResponsibleOffice_Number: !string
                default: ''
            RealEstate_RestrictionOnLandownership_ResponsibleOffice_PostalCode: !string
                default: ''
            RealEstate_RestrictionOnLandownership_ResponsibleOffice_City: !string
                default: ''
            RealEstate_PlanForLandRegister: !string {} #/definitions/Map
            RealEstate_Reference: !datasource
                default: []
                attributes: {}
            ExclusionOfLiability: !datasource
                default: []
                attributes:
                    Title: !datasource
                        attributes:
                            Language: !string {}
                            Text: !string {}
                    Content: !datasource
                        attributes:
                            Language: !string {}
                            Text: !string {}
            PLRCadastreAuthority_Name: !string {} #/definitions/MultilingualText
            PLRCadastreAuthority_OfficeAtWeb: !string {} #/definitions/WebReference
            PLRCadastreAuthority_UID: !string #/definitions/UID
                default: ''
            PLRCadastreAuthority_Line1: !string
                default: ''
            PLRCadastreAuthority_Line2: !string
                default: ''
            PLRCadastreAuthority_Street: !string {}
            PLRCadastreAuthority_Number: !string {}
            PLRCadastreAuthority_PostalCode: !string {}
            PLRCadastreAuthority_City: !string {}

            legend: !legend {}
            northArrow: !northArrow
                size: 40
                default:
                    graphic: "file:///north.svg"
            scalebar: !scalebar
                width: 150
                height: 20
                default:
                     fontSize: 8
            features: !features {}
            map: !map
                maxDpi: 254
                dpiSuggestions: [254]
                zoomLevels: !zoomLevels
                    scales: [100, 250, 500, 2500, 5000, 10000, 25000, 50000, 100000, 500000]
                width: 555
                height: 675
                default:
                    projection: "EPSG:21781"
                    dpi: 72
                    zoomToFeatures:
                        minScale: 2000
            overlayLayers: !staticLayers
                default:
                    layers:
                    -   type: geoJson
            style: !style
                default:
                    style:
                        version: 2
                        '*':
                            symbolizers:
                            -   type: polygon
                                fillColor: "#ff0000"

        processors:
        - !reportBuilder # compile all reports in current directory
            directory: '.'
        - !configureHttpRequests
            httpProcessors:
            - !forwardHeaders
                headers:
                - Referer
            - !restrictUris
                matchers:
                - !localMatch
                  reject: false
                #  reject: true
                - !ipMatch
                  ip: 10.0.0.0
                  mask: 255.0.0.0
                  reject: true
                - !ipMatch
                  ip: 172.16.0.0
                  mask: 255.240.0.0
                  reject: true
                - !ipMatch
                  ip: 192.168.0.0
                  mask: 255.255.0.0
                  reject: true
                - !acceptAll {}
        - !addOverlayLayers
            inputMapper:
                overlayLayers: staticLayers
        - !setStyle {}
        - !setFeatures {}
        - !createMap {}
        - !createNorthArrow {}
        - !createScalebar {}
        - !prepareLegend
            template: legend.jrxml
        - !createDataSource
            processors: []
            inputMapper:
                ConcernedTheme: datasource
            outputMapper:
                jrDataSource: ConcernedThemeDataSource
        - !createDataSource
            processors:
            - !createDataSource
                processors: []
                inputMapper:
                    Text: datasource
                outputMapper:
                    jrDataSource: TextDataSource
            inputMapper:
                NotConcernedTheme: datasource
            outputMapper:
                jrDataSource: NotConcernedThemeDataSource
        - !createDataSource
            processors: []
            inputMapper:
                ThemeWithoutData: datasource
            outputMapper:
                jrDataSource: ThemeWithoutDataDataSource
        - !createDataSource
            processors: []
            inputMapper:
                BaseData: datasource
            outputMapper:
                jrDataSource: BaseDataDataSource
