throwErrorOnExtraParameters: true


templates:
    A4 portrait: !template
        reportTemplate: A4_Portrait.jrxml
        attributes:
            CreationDate: !string {}
            Signature: !string &optStr
                default: ''
            ConcernedTheme: !datasource
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            NotConcernedTheme: !datasource
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            ThemeWithoutData: !datasource
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            isReduced: !boolean {}
            LogoPLRCadastre: *optStr
            LogoPLRCadastreRef: *optStr
            FederalLogo: *optStr
            FederalLogoRef: *optStr
            CantonalLogo: *optStr
            CantonalLogoRef: *optStr
            MunicipalityLogo: *optStr
            MunicipalityLogoRef: *optStr
            ExtractIdentifier: !string {}
            QRCode: *optStr
            QRCodeRef: *optStr
            GeneralInformation: !string #/definitions/MultilingualMText
                default: ''
            BaseData: !string {} #/definitions/MultilingualMText
            Glossary: !datasource
                default: []
                attributes:
                    Title: !string {} #/definitions/MultilingualText
                    Content: !string {} #/definitions/MultilingualText
            RealEstate_Number: !string {}
            RealEstate_IdentDN: !string {}
            RealEstate_EGRID: !string {}
            RealEstate_Type: !string {}
            RealEstate_Canton: !string {}
            RealEstate_Municipality: !string {}
            RealEstate_SubunitOfLandRegister: !string
                default: ''
            RealEstate_FosNr: !string {}
            RealEstate_MetadataOfGeographicalBaseData: !string
                default: ''
            RealEstate_LandRegistryArea: !string {}
            RealEstate_Limit: !string #/definitions/MultiSurface"
                default: '{}'
            RealEstate_RestrictionOnLandownership: !datasource
                default: []
                attributes:
                    Information: !string #/definitions/MultilingualMText
                        default: ''
                    Theme_Code: !string
                        default: ''
                    Theme_Text: !string #/definitions/LocalisedText
                        default: ''
                    SubTheme: !string
                        default: ''
                    TypeCode: !string #/definitions/RestrictiontypeCode
                        default: ''
                    TypeCodelist: !string
                        default: ''
                    Lawstatus: !string #/definitions/Lawstatus
                        default: ''
                    Area: !string #/definitions/Area
                        default: ''
                    PartInPercent: !float
                        default: -1
                    Symbol: !string
                        default: ''
                    SymbolRef: !string
                        default: ''
                    Geometry: !datasource
                        default: []
                        attributes:
                            Point: !string {} #/definitions/PointPropertyType
                            Line: !string {} #/definitions/CurvePropertyType
                            Surface: !string {} #/definitions/SurfacePropertyType
                            Lawstatus: !string {} #/definitions/Lawstatus
                            MetadataOfGeographicalBaseData: !string {}
                            ResponsibleOffice_Name: !string {} #/definitions/MultilingualText
                            ResponsibleOffice_OfficeAtWeb: !string {} #/definitions/WebReference
                            ResponsibleOffice_UID: !string #/definitions/UID
                                default: ''
                            ResponsibleOffice_Line1: !string
                                default: ''
                            ResponsibleOffice_Line2: !string
                                default: ''
                            ResponsibleOffice_Street: !string {}
                            ResponsibleOffice_Number: !string {}
                            ResponsibleOffice_PostalCode: !string {}
                            ResponsibleOffice_City: !string {}
                    Map: !string #/definitions/Map
                        default: '{}'
                    LegalProvisions: !datasource
                        default: []
                        attributes:
                          TextAtWeb: !string {} #/definitions/MultilingualUri
                          Lawstatus: !string {} #/definitions/Lawstatus
                          Number: *optStr #/definitions/ArticleNumber
                          Text: *optStr #/definitions/MultilingualMText
                          Title: *optStr #/definitions/MultilingualText
                          OfficialTitle: *optStr #/definitions/MultilingualText
                          Abbrevation: *optStr #/definitions/MultilingualText
                          OfficialNumber: *optStr
                          Canton: *optStr #/definitions/CantonCode
                          Municipality: *optStr #/definitions/MunicipalityCode
                          ResponsibleOffice: *optStr #/definitions/Office
                          OfficialNumber: *optStr #/definitions/CantonCode
                          ArticleNumber: *optStr #array of /definitions/ArticleNumber
                    ResponsibleOffice_Name: !string #/definitions/MultilingualText
                        default: ''
                    ResponsibleOffice_OfficeAtWeb: !string #/definitions/WebReference
                        default: ''
                    ResponsibleOffice_UID: !string #/definitions/UID
                        default: ''
                    ResponsibleOffice_Line1: !string
                        default: ''
                    ResponsibleOffice_Line2: !string
                        default: ''
                    ResponsibleOffice_Street: !string
                        default: ''
                    ResponsibleOffice_Number: !string
                        default: ''
                    ResponsibleOffice_PostalCode: !string
                        default: ''
                    ResponsibleOffice_City: !string
                        default: ''
            RealEstate_PlanForLandRegister: !string {} #/definitions/Map
            RealEstate_Reference: !datasource
                default: []
                attributes: {}
            ExclusionOfLiability: !datasource
                default: []
                attributes:
                    Title: !string {} #/definitions/MultilingualText
                    Content: !string {} #/definitions/MultilingualText
            PLRCadastreAuthority_Name: !string {} #/definitions/MultilingualText
            PLRCadastreAuthority_OfficeAtWeb: !string {} #/definitions/WebReference
            PLRCadastreAuthority_UID: !string #/definitions/UID
                default: ''
            PLRCadastreAuthority_Line1: !string
                default: ''
            PLRCadastreAuthority_Line2: !string
                default: ''
            PLRCadastreAuthority_Street: !string {}
            PLRCadastreAuthority_Number: !string {}
            PLRCadastreAuthority_PostalCode: !string {}
            PLRCadastreAuthority_City: !string {}

            legend: !legend {}
            northArrow: !northArrow
                size: 40
                default:
                    graphic: "file:///north.svg"
            scalebar: !scalebar
                width: 150
                height: 20
                default:
                     fontSize: 8
            features: !features {}
            map: !map
                maxDpi: 254
                dpiSuggestions: [254]
                zoomLevels: !zoomLevels
                    scales: [100, 250, 500, 2500, 5000, 10000, 25000, 50000, 100000, 500000]
                width: 555
                height: 675
                default:
                    projection: "EPSG:2056"
                    dpi: 72
                    zoomToFeatures:
                        minScale: 500
            overlayLayers: !staticLayers
                default:
                    layers:
                    -   type: geoJson
            style: !style
                default:
                    style:
                        version: 2
                        '*':
                            symbolizers:
                            -   type: polygon
                                fillColor: "#ff0000"

        processors:
        - !reportBuilder # compile all reports in current directory
            directory: '.'
        - !configureHttpRequests
            httpProcessors:
            - !forwardHeaders
                headers:
                - Referer
            - !restrictUris
                matchers:
                - !localMatch
                  reject: false
                #  reject: true
                - !ipMatch
                  ip: 10.0.0.0
                  mask: 255.0.0.0
                  reject: true
                - !ipMatch
                  ip: 172.16.0.0
                  mask: 255.240.0.0
                  reject: true
                - !ipMatch
                  ip: 192.168.0.0
                  mask: 255.255.0.0
                  reject: true
                - !acceptAll {}
        - !addOverlayLayers
            inputMapper:
                overlayLayers: staticLayers
        - !setStyle {}
        - !setFeatures {}
        - !createMap {}
        - !createNorthArrow {}
        - !createScalebar {}
        - !prepareLegend
            template: legend.jrxml
        - !createDataSource
            processors: []
            inputMapper:
                ConcernedTheme: datasource
            outputMapper:
                jrDataSource: ConcernedThemeDataSource
        - !createDataSource
            processors: []
            inputMapper:
                NotConcernedTheme: datasource
            outputMapper:
                jrDataSource: NotConcernedThemeDataSource
        - !createDataSource
            processors: []
            inputMapper:
                ThemeWithoutData: datasource
            outputMapper:
                jrDataSource: ThemeWithoutDataDataSource
        - !createDataSource
            processors: []
            inputMapper:
                Glossary: datasource
            outputMapper:
                jrDataSource: GlossaryDataSource
        - !createDataSource
            processors:
            - !createDataSource
                processors: []
                inputMapper:
                    Geometry: datasource
                outputMapper:
                    jrDataSource: GeometryDataSource
            - !createDataSource
                processors: []
                inputMapper:
                    LegalProvisions: datasource
                outputMapper:
                    jrDataSource: LegalProvisionsDataSource
            inputMapper:
                RealEstate_RestrictionOnLandownership: datasource
            outputMapper:
                jrDataSource: RealEstate_RestrictionOnLandownershipDataSource
        - !createDataSource
            processors: []
            inputMapper:
                RealEstate_Reference: datasource
            outputMapper:
                jrDataSource: RealEstate_ReferenceDataSource
        - !createDataSource
            processors: []
            inputMapper:
                ExclusionOfLiability: datasource
            outputMapper:
                jrDataSource: ExclusionOfLiabilityDataSource
